services:
  web:
    build:
      context: ./web
    container_name: lyrics-web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lyrics_db
  db:
    image: postgres:15
    container_name: lyrics-db
    environment:
      POSTGRES_PASSWORD: <password>
      POSTGRES_USER: ampache
      POSTGRES_DB: lyricsdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

